<div class="tabs">
  <div id="tab-1" class="tab">
    <article>
      <div class="text-section">
        <h1>Dashboard</h1>

        <ul class="dashboard-ul">
          <li>
            <div>
              <a href="<?= $this->url('admin-users') ?>">
                <span>User Management</span>
              </a>
            </div>
          </li>
          <li>
            <div>
              <a href="<?= $this->url('admin-blog') ?>">
                <span>Blog Management</span>
              </a>
            </div>
          </li>
          <li>
            <div>
              <a href="<?= $this->url('admin-pages') ?>">
                <span>Page Management</span>
              </a>
            </div>
          </li>
          <li>
            <div>
              <a href="<?= $this->url('admin-listing') ?>">
                <span>Listing Management</span>
              </a>
            </div>
          </li>
          <li>
            <div>
              <a href="<?= $this->url('admin-settings') ?>">
                <span>Setting Management</span>
              </a>
            </div>
          </li>
        </ul>
      </div>
    </article>
  </div>
</div>