<?php
#print_r($blog);
?>
<div class="aligncenter" style="margin-bottom: 10px;">
  <figure class="page2-img1"><img src="<?= $this->basePath() ?>/assests/images/blogs/top/<?= $blog->images ?>" width="940" height="132" alt=""></figure> 
</div>
<div class="pro_wrapper">  
  <article class="grid_9">
    <div class="page8-box1">
      <h3><?= $blog->title ?></h3>      
      <?= $blog->content ?>
    </div>
  </article>
  <article class="grid_3">
    <div class="page8-box1">
      <h3>Archives</h3>
      <ul class="list1">
        <li><a href="#">Etiam cursus leo vel metus</a></li>
        <li><a href="#">Nulla facilisi</a></li>
        <li><a href="#">Aenean nec eros</a></li>
        <li><a href="#">Vestibulum ante ipsum primis</a></li>
        <li><a href="#">In faucibus orci luctus et</a></li>
        <li><a href="#">Ultrices posuere cubilia Curae</a></li>
        <li><a href="#">Suspendisse sollicitudin velit sed</a></li>
        <li><a href="#">Ut pharetra augue nec augue</a></li>
        <li><a href="#">Nam elit agna,endrerit sit amet</a></li>
        <li><a href="#">Tincidunt ac, viverra sed, nulla</a></li>
        <li><a href="#">Donec porta diam eu massa</a></li>
        <li><a href="#">Quisque diam lorem</a></li>
        <li><a href="#">Interdum vitae,dapibus ac</a></li>
        <li><a href="#">Scelerisque vitae, pede</a></li>
        <li><a href="#">Donec eget tellus non erat</a></li>
        <li><a href="#">Lacinia fermentum</a></li>
        <li><a href="#">Donec in velit vel ipsum auctor</a></li>
        <li><a href="#">Vestibulum iaculis lacinia est</a></li>
      </ul>
    </div>
    <div class="page8-box1">
      <h3>Tag Cloud</h3>
      <?php
      $tags = $blog->keywords;
      if ($tags) :
        $tags_array = explode(",", $tags);
        foreach ($tags_array as $tag):
          ?>
          <a class="button2" href=""><?= $tag ?></a>
          <?php
        endforeach;
      endif;
      ?>
      <div class="clear"></div>
    </div>
  </article> 