<div class="wrapper">
  <article class="grid_4">
    <h4>Contact info</h4>
    <figure class="page6-img1">
      <img src="http://maps.googleapis.com/maps/api/staticmap?center=Dev+Arc,Mall+Ahmedabad,Gujrat&zoom=16&size=300x304&maptype=roadmap
           &markers=color:blue%7Clabel:S%7C23.025708,72.507663&sensor=false">
    </figure>
    <div class="clear"></div>
    <dl class="dl1">
      <dt>8901 Marmora Road, Glasgow, D04 89GR.</dt>
      <dd><span>Freephone:</span>+1 800 559 6580</dd>
      <dd><span>Telephone:</span>+1 800 603 6035</dd>
      <dd><span>FAX:</span>+1 800 889 9898</dd>
<!--      <dd>E-mail: <a href="#"><span class="__cf_email__" data-cfemail="573a363e3b1733323a383b3e393c79382530">[email&nbsp;protected]</span>
          </a></dd>-->@Fingertips33
    </dl>
  </article>
  <article class="grid_6 push_1">
    <h4>Get in touch</h4>
    <?= $this->form()->openTag($form); ?>
    <div class="success"><div class="success_txt">Contact form submitted!<br/><strong> We will be in touch soon.</strong></div></div>
    <fieldset>
      <label class="name">
        <?= $this->formRow($form->get('name')); ?>
        <span class="error">*This is not a valid name.</span> <span class="empty">*This field is required.</span>
      </label>
      <label class="email">
        <?= $this->formRow($form->get('email')); ?>
        <span class="error">*This is not a valid email address.</span> <span class="empty">*This field is required.</span>
      </label>
      <label class="phone">
        <?= $this->formRow($form->get('phone')); ?>
        <span class="error">*This is not a valid phone number.</span> <span class="empty">*This field is required.</span>
      </label>
      <label class="message">
        <?= $this->formRow($form->get('message')); ?>
        <span class="error">*The message is too short.</span> <span class="empty">*This field is required.</span> </label>
      <div class="clear"></div>
      <div class="link-form">
        <a class="link1 p29" href="#" data-type="reset">Clear</a>
        <a class="link1" href="#" data-type="submit">Submit</a>
      </div>
    </fieldset>
    <?= $this->form()->closeTag(); ?>
  </article>
</div>