<?php

/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
return array(
    'guest' => array(
        'admin-login',
        'user_login',
        'home',
        'contact',
        'application',
        'blog',
        'blog-detail',
        'blog-search',
        'blog-crud',
        'forgot-password',
    ),
    'admin' => array(
        /**
         * Admin Access
         */
        'admin',
        'admin-logout',
        'admin-auth-index',
        /**
         * Admin Blog
         */
        'admin-blog',
        'admin-blog-delete',
        'admin-blog-view',
        'admin-blog-edit',
        /**
         * Admin Users
         */
        'admin-users',
        'admin-user-edit',
        'admin-user-view',
        'admin-user-delete',
        'admin-crud-user',
        'admin-crud-users',
        /**
         * Admin Pages
         */
        'admin-pages',
        'admin-page-edit',
        'admin-page-view',
        'admin-page-delete',
        'admin-page-new',
        /**
         * Admin Lists
         */
        'admin-listing',
        /**
         * Admin Settings
         */
        'admin-settings',
        'admin-setting-edit',
        /**
         * General Access
         */
//        'home',
//        'contact',
//        'application',
//        'blog',
//        'blog-detail',
//        'blog-search',
//        'blog-crud',
//        'user_home',
//        'user-logout',
//        'profile',
    ),
    'user' => array(
        #'home',
        #'contact',
        #'application',
        #'blog',
        #'blog-detail',
        #'blog-search',
        #'blog-crud',
        #'user-logout',
        #'profile',
    )
);
