<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'User\Module'                     => __DIR__ . '/Module_1.php',
    'User\Model\Authenticate'         => __DIR__ . '/src/User/Model/Authenticate.php',
    'User\Model\Table\UserTable'      => __DIR__ . '/src/User/Model/Table/UserTable.php',
    'User\Model\User'                 => __DIR__ . '/src/User/Model/User.php',
    'User\Traits\Session'             => __DIR__ . '/src/User/Traits/Session.php',
    'User\Storage\AuthStorage'        => __DIR__ . '/src/User/Storage/AuthStorage.php',
    'User\Controller\AuthController'  => __DIR__ . '/src/User/Controller/AuthController.php',
    'User\Controller\IndexController' => __DIR__ . '/src/User/Controller/IndexController.php',
    'User\Form\Validator\Auth'        => __DIR__ . '/src/User/Form/Validator/Auth.php',
    'User\Form\Auth'                  => __DIR__ . '/src/User/Form/Auth.php',
    'User\View\Helper\Session'        => __DIR__ . '/src/User/View/Helper/Session.php',
    'User\View\Helper\User'           => __DIR__ . '/src/User/View/Helper/User.php',
);
