<div class="wrapper p7">
  <article class="grid_12">
    <div class="page1-box1">
      <div class="inner1">
        <span class="text1">Latest Real Estate strategies and tips</span>
        <p>Lorem ipsum dolor sit amet consectetuer adipiscing elit. Praesent vestibu</p>
      </div>
      <a class="button1 fright p6" href="">Read More</a>
      <div class="clear"></div>
    </div>
  </article>
</div>
<div class="wrapper p9">
  <article class="grid_4">
    <h4>Market</h4>
    <div class="page1-box2">
      <p class="p8">Lorem ipsum dolor sit amet coetuer adipiscing
        elit. Praesent vestibulum molestie lacus. Aenean nonummy hendrerit mauris. Phasellus. Fusce suscipit varius mi. Cum socinoque penatib
        us et mais dis parturites.</p>
      <a class="link1" href="">Read More</a>
    </div>
  </article>
  <article class="grid_4">
    <h4>Why us?</h4>
    <div class="page1-box2">
      <p class="p8">Praesent vestibulm mostie lacus. Aeneanmmy
        hendrerit mauris. Phases po. Fusce suscipit var mi. Cum sociis natoque pentis et mais dis parttones nastur rid mus. Nulla dui. Fusce feu
        giat malesuaddio. Morbi nunc.</p>
      <a class="link1" href="">Read More</a>
    </div>
  </article>
  <article class="grid_4">
    <h4>Contacts</h4>
    <dl class="dl2">
      <dt>8901 Marmora Road, Glasgow, D04 89GR.</dt>
      <dd><span>Freephone:</span> +1 800 559 6580</dd>
      <dd><span>Telephone:</span> +1 800 603 6035</dd>
      <dd><span>FAX:</span> +1 800 889 9898</dd>
    </dl>
    <a class="link1" href="">Read More</a>
  </article>
</div>
<div class="wrapper">
  <article class="grid_12">
    <div class="page1-box1 p10">
      <span class="text2 fleft">Top of the Market</span>
      <a class="link1 fright" href="">View All Offers</a>
      <div class="clear"></div>
    </div>
  </article>
</div>
<div class="wrapper">
  <article class="grid_4">
    <div class="page1-box3">
      <a class="link-bot" href=""><img src="<?= $this->basePath() ?>/assests/images/page1-img1.jpg" class="grey" alt=""/>
        <img src="<?= $this->basePath() ?>/assests/images/page1-img1-color.jpg" class="color" alt=""/></a>
      <a class="link2 fleft" href="">Lorem ipsum dolor</a>
      <span class="text3 fright">$340`000</span>
      <div class="clear"></div>
    </div>
    <div class="page1-box3 last1">
      <a class="link-bot" href=""><img src="<?= $this->basePath() ?>/assests/images/page1-img2.jpg" class="grey" alt=""/>
        <img src="<?= $this->basePath() ?>/assests/images/page1-img2-color.jpg" class="color" alt=""/></a>
      <a class="link2 fleft" href="">Aenean nec eronte ipss</a>
      <span class="text3 fright">$2`320`000</span>
      <div class="clear"></div>
    </div>
  </article>
  <article class="grid_4">
    <div class="page1-box3">
      <a class="link-bot" href=""><img src="<?= $this->basePath() ?>/assests/images/page1-img3.jpg" class="grey" alt=""/>
        <img src="<?= $this->basePath() ?>/assests/images/page1-img3-color.jpg" class="color" alt=""/></a>
      <a class="link2 fleft" href="">Aenean nec eronte ipss</a>
      <span class="text3 fright">$867`000</span>
      <div class="clear"></div>
    </div>
    <div class="page1-box3 last1">
      <a class="link-bot" href=""><img src="<?= $this->basePath() ?>/assests/images/page1-img4.jpg" class="grey" alt=""/>
        <img src="<?= $this->basePath() ?>/assests/images/page1-img4-color.jpg" class="color" alt=""/></a>
      <a class="link2 fleft" href="">Voluptatem accusantium </a>
      <span class="text3 fright">$780`000</span>
      <div class="clear"></div>
    </div>
  </article>
  <article class="grid_4">
    <div class="page1-box3">
      <a class="link-bot" href=""><img src="<?= $this->basePath() ?>/assests/images/page1-img5.jpg" class="grey" alt=""/>
        <img src="<?= $this->basePath() ?>/assests/images/page1-img5-color.jpg" class="color" alt=""/></a>
      <a class="link2 fleft" href="">Esit voluptatem accusantium</a>
      <span class="text3 fright">$1`560`000</span>
      <div class="clear"></div>
    </div>
    <div class="page1-box3 last1">
      <a class="link-bot" href=""><img src="<?= $this->basePath() ?>/assests/images/page1-img6.jpg" class="grey" alt=""/>
        <img src="<?= $this->basePath() ?>/assests/images/page1-img6-color.jpg" class="color" alt=""/></a>
      <a class="link2 fleft" href="">Lorem ipsum dolor</a>
      <span class="text3 fright">$540`000</span>
      <div class="clear"></div>
    </div>
  </article>
</div>