<?php echo $this->headLink()->prependStylesheet($this->basePath() . '/assests/admin/css/popup.css?r=' . rand(0, 9999)) ?>
<article>
  <h1>Edit Settings</h1>
  <div class="form-container">

    <?php
    $form = $this->form;
    $form->setAttribute('action', '');
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
    ?>
  </div>      
</article>
