<div class="tabs">
  <div id="tab-1" class="tab">
    <article>
      <div class="text-section">
        <h1>Settings</h1>
        <div class="listing">
          <div id="search_wrapper">          
            <?php
            /**
             * set uri prams
             */
            $uri_params = $page_params;
            unset($uri_params['order_by']);
            $uri_params = array_filter($uri_params);
            $uri_params['order'] = $order;
            /**
             * Setup search form
             */
            $form = $this->search_form;
            $form->prepare();
            echo $this->form()->openTag($form);
            echo $this->formCollection($form);
            echo $this->form()->closeTag();
            ?>
            <div class="clear"></div>
          </div>
          <table id="admin-setting-list" name="admin-setting-list" border="0" width="100%">
            <thead>
              <tr>
                <th width="5%">                  
                  <a href="<?= $this->url('admin-settings', array_merge($uri_params, array("page" => $page, "order_by" => "setting_id"))) ?>">
                    ID.
                  </a>
                </th>
                <th width="35%">
                  <a href="<?= $this->url('admin-settings', array_merge($uri_params, array("page" => $page, "order_by" => "name"))) ?>">
                    Setting Key
                  </a>
                </th>               
                <th width="50%">
                  <a href="<?= $this->url('admin-settings', array_merge($uri_params, array("page" => $page, "order_by" => "value"))) ?>">
                    Setting Value
                  </a>
                </th>               
                <th width="5%">&nbsp;</th>                
                <th width="5%">&nbsp;</th>

              </tr>
            </thead>
            <tbody>
              <?php if (sizeof($paginator) > 0): ?>
                <?php foreach ($paginator as $setting): ?>
                  <tr>
                    <td align="middle"><?= $setting->id ?></td>                                   
                    <td align="middle"><?= $setting->key ?></td>
                    <td align="middle"><?= $setting->value ?></td>                                                                             
                    <td align="middle">
                      <a height="40%" width="60%"  class="various fancybox.iframe" href="<?= $this->url("admin-setting-edit", array("id" => $setting->id, "page" => $page)) ?>">
                        Edit
                      </a>
                    </td>                                                                             
                    <td align="middle">
                      <a class="various fancybox.iframe" href="<?= $this->url("admin-page-delete", array("id" => $setting->id, "page" => $page)) ?>">
                        Delete
                      </a>
                    </td>                                                                             
                  </tr>
                <?php endforeach; ?>          
              <?php else: ?>
                <tr  height="50" >
                  <td colspan="5" align="middle" valign="center">
                    No record(s) found.
                  </td>
                </tr>
              <?php endif; ?>

              <tr  class="no-border">
                <td colspan="5" align="right" valign="center">
                  <div id="admin-paginator-wrapper">
                    <?php
                    $params = array(
                        "route" => "admin-settings",
                        "page_params" => array_filter($page_params),
                    );
                    echo $this->paginationControl($paginator, 'Sliding', 'admin-paginator-slide', $params);
                    ?>
                  </div>
                </td>
              </tr>
          </table>         
        </div>
      </div>
    </article>
  </div>
</div>
