<div class="tabs">
  <div id="tab-1" class="tab">
    <article>
      <div class="text-section">
        <h1>Pages</h1>
        <div class="listing">
          <div id="search_wrapper">          
            <?php
            /**
             * set uri prams
             */
            $uri_params = $page_params;
            unset($uri_params['order_by']);
            $uri_params = array_filter($uri_params);
            $uri_params['order'] = $order;
            /**
             * Setup search form
             */
            $form = $this->search_form;
            $form->prepare();
            echo $this->form()->openTag($form);
            echo $this->formCollection($form);
            echo $this->form()->closeTag();
            ?>
            <div class="clear"></div>
          </div>
          <table id="admin-page-list" name="admin-page-list" border="0" width="100%">
            <thead>
              <tr>
                <th width="5%">
                  <a href="<?= $this->url('admin-pages', array_merge($uri_params, array("page" => $page, "order_by" => "page_id"))) ?>">
                    ID
                  </a>
                </th>
                <th width="10%">
                  <a href="<?= $this->url('admin-pages', array_merge($uri_params, array("page" => $page, "order_by" => "page_title"))) ?>">
                    Title
                  </a>
                </th>
                <th width="10%">
                  <a href="<?= $this->url('admin-pages', array_merge($uri_params, array("page" => $page, "order_by" => "username"))) ?>">
                    Owner
                  </a>
                </th>
                <th width="40%">
                  <a href="<?= $this->url('admin-pages', array_merge($uri_params, array("page" => $page, "order_by" => "page_description"))) ?>">
                    Description
                  </a>
                </th>              
                <th width="15%">
                  <a href="<?= $this->url('admin-pages', array_merge($uri_params, array("page" => $page, "order_by" => "page_date"))) ?>">
                    Date
                  </a>
                </th>
                <th width="5%">
                  <a href="<?= $this->url('admin-pages', array_merge($uri_params, array("page" => $page, "order_by" => "page_status"))) ?>">
                    Status
                  </a>
                </th>
                <th width="5%">&nbsp;</th>
                <th width="5%">&nbsp;</th>
                <th width="5%">&nbsp;</th>

              </tr>
            </thead>
            <tbody>
              <?php if (sizeof($paginator) > 0): ?>
                <?php foreach ($paginator as $pages): ?>
                  <tr>
                    <td align="middle"><?= $pages->page_id ?></td>
                    <td><?= $pages->title ?></td>
                    <td align="middle"><?= $pages->owner ?></td>
                    <td align="middle"><?= $pages->description ?></td>                
                    <td align="middle"><?= $pages->date ?></td>
                    <td align="middle"><?= $pages->status ?></td>                                                                             
                    <td align="middle">
                      <a class="various fancybox.iframe" href="<?= $this->url("admin-page-view", array("page_id" => $pages->page_id, "page" => $page)) ?>">
                        View
                      </a>
                    </td>                                                                             
                    <td align="middle">
                      <a title="250px" href="<?= $this->url("admin-page-edit", array("page_id" => $pages->page_id, "page" => $page)) ?>">
                        Edit
                      </a>
                    </td>                                                                             
                    <td align="middle">
                      <a height="30%" width="60%" class="various fancybox.iframe" href="<?= $this->url("admin-page-delete", array("page_id" => $pages->page_id, "page" => $page)) ?>">
                        Delete
                      </a>
                    </td>                                                                             
                  </tr>
                <?php endforeach; ?>          
              <?php else: ?>
                <tr  height="50" >
                  <td colspan="9" align="middle" valign="center">
                    No record(s) found.
                  </td>
                </tr>
              <?php endif; ?>

              <tr  class="no-border">
                <td colspan="11" align="right" valign="center">
                  <div id="admin-paginator-wrapper">
                    <?php
                    $params = array(
                        "route" => "admin-pages",
                        "page_params" => array_filter($page_params),
                    );
                    echo $this->paginationControl($paginator, 'Sliding', 'admin-paginator-slide', $params);
                    ?>
                  </div>
                </td>
              </tr>
          </table>         
        </div>
      </div>
    </article>
  </div>
</div>
