<?php
#print_r($blog);
?>
<div class="aligncenter bg_detc">
  <div class="pro_curved-vt-2 wid-98">
    <div class="pro_text-shadow">    
      <figure class="page2-img1">
        <img src="<?= $this->basePath() ?>/assests/images/blogs/top/<?= $blog->images ?>" width="900" height="300" alt="">
      </figure> 
    </div>
  </div>
</div>
<!--<div class="pro_buttons_pad" style="margin:15px 0px;">
  <a id="click_me" href="#" class="pro_btn pro_style_3 pro_notClicked">Click me!</a>
</div>-->
<div class="pro_wrapper">  
  <article class="grid_9">
    <div class="pro_curved-vt-2">
      <div class="pro_text-shadow left-a-just">        
        <h3><?= $blog->title ?></h3>      
        <?= $blog->content ?>

      </div>    
      <div class="clear"></div>  
    </div>

    <?php
    $comments = $this->blog()->comments($blog->blog_id, 'Blog\Model\CommentTable', 5);
    if (sizeof($comments) > 0):
      ?>
      <h4>Comments</h4>
      <div class = "grid_9 alpha">
        <?php foreach ($comments as $comment): ?>
          <div class="pro_curved-hz-2">
            <div class="pro_text-shadow left-a-just">
              <blockquote>
                <?= $comment->content ?>
                <br>
                <a href = "#"><em><?= ucfirst(strtolower($comment->username)) ?></em></a><br />
                On 
                <time datetime="<?= $blog->create_date ?>"><?= date("jS F, Y", strtotime($comment->comment_date)) ?></time> 
              </blockquote>
            </div>
          </div>
        <?php endforeach; ?>
      </div>
    <?php endif; ?>
  </article>
  <article class="grid_3">
    <div class="page8-box1">

      <div class="pro_curved-hz-2">
        <div class="pro_text-shadow left-a-just">        
          <h4>Archives</h4>
          <ul class="list1">
            <?php
            $archiveBlogs = $this->blog()->archives('Blog\Model\BlogTable');
            $occr = array(" ", "'", ".", ",");
            $rep = array("-", '', "-", "-");
            if (sizeof($archiveBlogs) > 0) {
              foreach ($archiveBlogs as $archive) {
                ?>
                <li><a href="<?= $this->url('blog-detail', array("id" => $archive->blog_id, 'title' => str_replace($occr, $rep, $archive->title))) ?>"><?= $archive->title ?></a></li>
                <?php
              }
            }
            ?>
          </ul>       
        </div>
      </div>
    </div>
    <div class="clear"></div>
    <div class="page8-box1">      
      <div class="pro_curved-hz-2">
        <div class="pro_text-shadow left-a-just">        
          <h4>Tag Cloud</h4>
          <?php
          $tags = $blog->keywords;
          if ($tags) :
            $tags_array = explode(",", $tags);
            foreach ($tags_array as $tag):
              $tag_det = explode("::", $tag);
              ?>
              <a class="button2" href="<?= $this->url('blog', array('tag_id' => $tag_det[0], 'tag' => strtolower($tag_det[1]), 'category' => null, 'category_title' => null)) ?>"><?= $tag_det[1] ?></a>
              <?php
            endforeach;
          endif;
          ?>
          <div class="clear"></div>
        </div>
      </div>

    </div>
  </article> 