<?php echo $this->doctype(); ?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php
    echo $this->headTitle('Admin - Zend Framework 2 Admin Interface')
            ->setSeparator(' - ')
            ->setAutoEscape(false);
    echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0');

    echo $this->headLink()
            ->prependStylesheet($this->basePath() . '/assests/admin/css/style.css');

    echo $this->headScript()->prependFile($this->basePath() . '/assests/admin/js/script.js')
            ->prependFile($this->basePath() . '/assests/admin/js/jquery-1.7.1.min')
            ->prependFile($this->basePath() . '/assests/admin/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',));
    ?>

  </head>

  <body>

    <div class="navbar">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?php echo $this->url('admin') ?>">Admin</a>
          <div class="nav-collapse">
            <?php
            echo $this->navigation('admin_navigation')
                    ->menu()
                    ->setUlClass('nav')
                    ->setMaxDepth(0)
                    ->setRenderInvisible(false)
            ?>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

      <?php echo $this->content; ?>

      <hr>

      <footer>
        <p>&copy; 2005 - 2012 by Zend Technologies Ltd. All rights reserved.</p>
      </footer>

    </div> <!-- /container -->

    <?php echo $this->inlineScript() ?>
  </body>
</html>
