<?php
$session = $this->adminSession()->getSession();
?>
<div class="controls">
  <!--  <nav class="links">
      <ul>
        <li><a href="#" class="ico1">Messages <span class="num">26</span></a></li>
        <li><a href="#" class="ico2">Alerts <span class="num">5</span></a></li>
        <li><a href="#" class="ico3">Documents <span class="num">3</span></a></li>
      </ul>
    </nav>-->
  <div class="profile-box">
    <span class="profile">
      <a href="#" class="section">
        <img class="image" src="<?= $this->basePath() . $session->admin->image_controls ?>" alt="<?= $session->admin->name ?>" width="26" height="26" />
        <span class="text-box">
          Welcome
          <strong class="name"><?= $session->admin->name ?></strong>
        </span>
      </a>
      <a href="#" class="opener">opener</a>
    </span>
    <a href="<?= $this->url('admin-logout') ?>" title="log-out" class="btn-on">On</a>
  </div>
</div>