<?php echo $this->doctype(); ?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php
    echo $this->headTitle('Admin - Zend Framework 2 Admin Interface')
            ->setSeparator(' - ')
            ->setAutoEscape(false);
    echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0');

    echo $this->headLink()
            ->prependStylesheet($this->basePath() . '/assests/admin/css/popup.css?r=' . rand(0, 9999))
            ->prependStylesheet($this->basePath() . '/assests/admin/plugins/fancyBox2/source/jquery.fancybox.css?v=2.1.5');

    echo $this->headScript()->prependFile($this->basePath() . '/assests/admin/js/script.js')
            ->prependFile($this->basePath() . '/assests/admin/plugins/fancyBox2/lib/jquery.mousewheel-3.0.6.pack.js')
            ->prependFile($this->basePath() . '/assests/admin/plugins/fancyBox2/source/jquery.fancybox.pack.js?v=2.1.5')
            ->prependFile($this->basePath() . '/assests/admin/js/jquery-1.10.1.min.js')
            ->prependFile($this->basePath() . '/assests/admin/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',));
    ?>

  </head>
  <body>
    <?php echo $this->content; ?>      
    <?php echo $this->inlineScript() ?>
  </body>
</html>
