<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Blog\Module'                     => __DIR__ . '/Module.php',
    'Blog\Model\Category'             => __DIR__ . '/src/Blog/Model/Category.php',
    'Blog\Model\Table\CommentTable'   => __DIR__ . '/src/Blog/Model/Table/CommentTable.php',
    'Blog\Model\Table\CategoryTable'  => __DIR__ . '/src/Blog/Model/Table/CategoryTable.php',
    'Blog\Model\Table\BlogTable'      => __DIR__ . '/src/Blog/Model/Table/BlogTable.php',
    'Blog\Model\Blogs'                => __DIR__ . '/src/Blog/Model/Blogs.php',
    'Blog\Model\Comment'              => __DIR__ . '/src/Blog/Model/Comment.php',
    'Blog\Controller\CrudController'  => __DIR__ . '/src/Blog/Controller/CrudController.php',
    'Blog\Controller\IndexController' => __DIR__ . '/src/Blog/Controller/IndexController.php',
    'Blog\View\Helper\Blog'           => __DIR__ . '/src/Blog/View/Helper/Blog.php',
);
