<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Module'                       => __DIR__ . '/Module.php',
    'Application\Model\ContactTable'           => __DIR__ . '/src/Application/Model/ContactTable.php',
    'Application\Model\Contact'                => __DIR__ . '/src/Application/Model/Contact.php',
    'Application\Controller\IndexController'   => __DIR__ . '/src/Application/Controller/IndexController.php',
    'Application\Controller\ContactController' => __DIR__ . '/src/Application/Controller/ContactController.php',
    'Application\Controller\UserController' => __DIR__ . '/src/Application/Controller/UserController.php',
    'Application\Form\Contact'                 => __DIR__ . '/src/Application/Form/Contact.php',
    'Application\Form\ContactValidator'        => __DIR__ . '/src/Application/Form/ContactValidator.php',
    'Application\View\Helper\AbsoluteUrl'      => __DIR__ . '/src/Application/View/Helper/AbsoluteUrl.php',
    'Application\View\Helper\Params'           => __DIR__ . '/src/Application/View/Helper/Params.php',
);
