<footer class="p22">
  <div class="container_12">
    <div class="wrapper p14">
      <article class="grid_4">
        <h4 class="p12">Gallery</h4>
        <div class="foot-page1">
          <a href="<?= $this->basePath() ?>/assests/images/image-blank.png" data-gal="prettyPhoto[gallery1]" class="lightbox-image link-bot"><img src="<?= $this->basePath() ?>/assests/images/page1-img7.jpg" height="77" width="77" alt=""/></a>
          <a href="<?= $this->basePath() ?>/assests/images/image-blank.png" data-gal="prettyPhoto[gallery1]" class="lightbox-image link-bot"><img src="<?= $this->basePath() ?>/assests/images/page1-img8.jpg" height="77" width="77" alt=""/></a>
          <a href="<?= $this->basePath() ?>/assests/images/image-blank.png" data-gal="prettyPhoto[gallery1]" class="lightbox-image link-bot"><img src="<?= $this->basePath() ?>/assests/images/page1-img9.jpg" height="77" width="77" alt=""/></a>
          <div class="clear"></div>
          <a href="<?= $this->basePath() ?>/assests/images/image-blank.png" data-gal="prettyPhoto[gallery1]" class="lightbox-image link-bot"><img src="<?= $this->basePath() ?>/assests/images/page1-img10.jpg" height="77" width="77" alt=""/></a>
          <a href="<?= $this->basePath() ?>/assests/images/image-blank.png" data-gal="prettyPhoto[gallery1]" class="lightbox-image link-bot"><img src="<?= $this->basePath() ?>/assests/images/page1-img11.jpg" height="77" width="77" alt=""/></a>
          <a href="<?= $this->basePath() ?>/assests/images/image-blank.png" data-gal="prettyPhoto[gallery1]" class="lightbox-image link-bot"><img src="<?= $this->basePath() ?>/assests/images/page1-img12.jpg" height="77" width="77" alt=""/></a>
          <div class="clear"></div>
        </div>
      </article>
      <article class="grid_4">
        <h4 class="p12">About Us</h4>
        <span class="text4">Praesent vestibulm mostie laenean mmy </span>
        <p>Fusce suscipit var mi. Cum sociis natoque pentis et mais dis parttones nastur rid mus. Nulla dui. Fusce feiat malesuaddio. Morbi nuncodio gravaecenas tristique orci ac sem. Duis ultrici.</p>
        <a class="link1" href="">Read More</a>
      </article>
      <article class="grid_4">
        <h4 class="p13">Tags</h4>
        <a class="button2" href="">house</a>
        <a class="button2" href="">villa</a>
        <a class="button2" href="">pool</a>
        <a class="button2" href="">real estate</a>
        <div class="clear"></div>
        <a class="button2" href="">bedroom</a>
        <a class="button2" href="">flat</a>
        <a class="button2" href="">commercial</a>
        <a class="button2" href="">view</a>
        <div class="clear"></div>
        <a class="button2" href="">residential</a>
        <a class="button2" href="">luxury</a>
        <div class="clear"></div>
      </article>
    </div>
    <div class="wrapper">
      <article class="grid_4">
        <div class="foot-page1">ZendFramework-Vikas &copy; 2013 • <a href="">Privacy Policy</a><div class="clear"></div> </div>
      </article>
    </div>
  </div>
</footer>