
<header>
  <div class="main">
    <div class="head-box1">
      <h1><a class="logo" href="<?= $this->url('home') ?>">Zendframework</a></h1>
      <div class="fright">
        <ul class="soc-links">
          <li><a class="soc-link1" href="#"></a></li>
          <li><a class="soc-link2" href="#"></a></li>
          <li><a class="soc-link3" href="#"></a></li>
          <li><a class="soc-link4" href="#"></a></li>
          <li><a class="soc-link5" href="#"></a></li>
        </ul>
        <div class="clear"></div>
        <?php echo $this->render('layout/navigation.phtml'); ?>
      </div>
      <div class="clear"></div>
    </div>
    <?php
    echo $this->render('layout/slider.phtml');
    ?>
  </div>
</header>
